import { useEffect,useState } from 'react';
import { openServerPrint, type Me } from '../../api.ts';
import { Link } from '../../router.tsx';
import { Button,Field,Notice,Panel,inputClass,peso } from '../../components/ui.tsx';
import { BookTitle,Tools,useReport,useToday,td,th } from './Books.tsx';
type Result={rows:Record<string,unknown>[]};
const labels:Record<string,string>={apAging:'AP aging',purchases:'Purchases by supplier and category',purchaseOrders:'Purchase orders by status',receivedNotBilled:'Received but not billed',cashPosition:'Cash position',transfers:'Transfers',cashCounts:'Cash counts',assets:'Fixed-asset schedule',lateEntries:'Late entries',cancellations:'Cancellations and reissues',exceptions:'Exceptions',signIns:'Sign-in history'};
const endpoints:Record<string,string>={apAging:'ap-aging',purchases:'purchases',purchaseOrders:'purchase-orders',receivedNotBilled:'received-not-billed',cashPosition:'cash-position',transfers:'transfers',cashCounts:'cash-counts',assets:'assets',lateEntries:'late-entries',cancellations:'cancellations',exceptions:'exceptions',signIns:'sign-ins'};
const ranges=new Set(['purchases','transfers','cashCounts','signIns']), dated=new Set(['apAging','cashPosition','assets','exceptions']);
function Report({me,kind}:{me:Me;kind:string}){const today=useToday(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[applied,setApplied]=useState('');useEffect(()=>{if(today&&!to){setTo(today);setFrom(today.slice(0,7)+'-01')}},[today,to]);useEffect(()=>{if(today&&!applied)setApplied(ranges.has(kind)?new URLSearchParams({from:today.slice(0,7)+'-01',to:today}).toString():dated.has(kind)?new URLSearchParams({asOf:today}).toString():'ready')},[today,applied,kind]);const query=applied==='ready'?'':`?${applied}`,path=applied?`${endpoints[kind]}${query}`:null,{data,error}=useReport<Result>(path);if(!me.permissions.includes('rpt.books.view'))return <Notice>Access denied.</Notice>;const keys=[...new Set((data?.rows??[]).flatMap(Object.keys))].filter(k=>!['id','documentPath','replacementPath'].includes(k));const show=()=>setApplied(ranges.has(kind)?new URLSearchParams({from,to}).toString():new URLSearchParams({asOf:to}).toString());return <article className="rpt-page space-y-4"><BookTitle title={labels[kind]!} dates=""/><div className="flex flex-wrap items-end gap-3 print:hidden">{ranges.has(kind)&&<Field label="From"><input type="date" className={inputClass} value={from} onChange={e=>setFrom(e.target.value)}/></Field>}{(ranges.has(kind)||dated.has(kind))&&<Field label={dated.has(kind)?'As of':'To'}><input type="date" className={inputClass} value={to} onChange={e=>setTo(e.target.value)}/></Field>}{(ranges.has(kind)||dated.has(kind))&&<Button tone="primary" onClick={show}>Show</Button>}{path&&<Tools path={path}/>} {kind==='assets'&&data&&<Button onClick={()=>void openServerPrint(me,'/api/prt/reports/fixed-assets',{asOf:to})}>Print fixed asset schedule</Button>}</div>{error&&<Notice>{error}</Notice>}{data&&<Panel title={`${data.rows.length} rows`}><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{keys.map(k=><th className={th} key={k}>{k.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{data.rows.map((r,i)=><tr key={i}>{keys.map(k=><td className={td} key={k}>{k==='number'&&r.documentPath?<Link className="text-indigo-700 underline" to={String(r.documentPath)}>{String(r[k]??'')}</Link>:k.endsWith('Cents')&&typeof r[k]==='number'?peso(r[k] as number):String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></Panel>}</article>}
export const ApAging=(p:{me:Me})=><Report {...p} kind="apAging"/>;export const Purchases=(p:{me:Me})=><Report {...p} kind="purchases"/>;export const PurchaseOrders=(p:{me:Me})=><Report {...p} kind="purchaseOrders"/>;export const ReceivedNotBilled=(p:{me:Me})=><Report {...p} kind="receivedNotBilled"/>;export const CashPosition=(p:{me:Me})=><Report {...p} kind="cashPosition"/>;export const Transfers=(p:{me:Me})=><Report {...p} kind="transfers"/>;export const CashCounts=(p:{me:Me})=><Report {...p} kind="cashCounts"/>;export const Assets=(p:{me:Me})=><Report {...p} kind="assets"/>;export const LateEntries=(p:{me:Me})=><Report {...p} kind="lateEntries"/>;export const Cancellations=(p:{me:Me})=><Report {...p} kind="cancellations"/>;export const Exceptions=(p:{me:Me})=><Report {...p} kind="exceptions"/>;export const SignIns=(p:{me:Me})=><Report {...p} kind="signIns"/>;
