export type DecisionGroup = 'accountant' | 'owner' | 'co-owners';
export interface DecisionDefinition { id: string; group: DecisionGroup; question: string; defaultAnswer: string; when: string; settingKey?: string }

/** PLAN Part K, copied verbatim so the register stays useful even when printed offline. */
export const PART_K_DECISIONS: DecisionDefinition[] = [
  { id: 'ACC-01', group: 'accountant', question: 'When is a sale and receivable booked: at the manual invoice record, required at release (option B)?', defaultAnswer: 'B', when: 'Before go-live' },
  { id: 'ACC-02', group: 'accountant', question: 'Downpayment VAT: A deposit only, B VAT on deposit, or C a manual invoice for each downpayment?', defaultAnswer: 'A', when: 'Before go-live', settingKey: 'sales.deposit_vat_mode' },
  { id: 'ACC-03', group: 'accountant', question: 'May the ERP print its own system-numbered COLLECTION RECEIPT without registration, or must CRs come from an ATP booklet? Exact legend and required CR fields? Are leftover ORs used as supplementary receipts?', defaultAnswer: 'Booklet mode', when: 'Before go-live', settingKey: 'col.cr_mode' },
  { id: 'ACC-04', group: 'accountant', question: 'Books: manual books transcribed from ERP reports, or loose-leaf (PTU) printed from the ERP? Which books are registered now? ERP stays unregistered (not CAS)?', defaultAnswer: 'ERP unregistered; loose-leaf layouts available', when: 'Before go-live' },
  { id: 'ACC-05', group: 'accountant', question: 'Past months with no SSS/PhilHealth/Pag-IBIG/WTax: catch-up method, who bears employee shares, PhilHealth interest waiver (open until 31 Dec 2026)', defaultAnswer: 'Exposure report only; no automatic catch-up', when: 'Before Dec 2026' },
  { id: 'ACC-06', group: 'accountant', question: 'Is Virtus a published Top Withholding Agent? Which EWT applies (rent 5%, contractors/printers 2%, professional fees)? Is the landlord VAT-registered, and is ₱40,000 gross? Accountant/notary: individual or firm?', defaultAnswer: 'Rent 5%, contractors 2%, professional 10% without sworn declaration; not TWA', when: 'Before go-live', settingKey: 'tax.top_withholding_agent' },
  { id: 'ACC-06b', group: 'accountant', question: 'Piece workers earning below the minimum wage for days worked: add a top-up line automatically?', defaultAnswer: 'Warn only', when: 'Before first payroll' },
  { id: 'ACC-07', group: 'accountant', question: "Made-to-order garments: goods or services (affects the customer's 1%/2% CWT and ACC-02)?", defaultAnswer: 'Goods for CWT expectation; CWT typed as actually withheld', when: 'Before go-live' },
  { id: 'ACC-08', group: 'accountant', question: 'Wrong manual invoice procedure and credit memo form (ATP booklet or ERP form)?', defaultAnswer: 'Cancel with all copies kept + replacement; CM by accountant', when: 'Before go-live' },
  { id: 'ACC-09', group: 'accountant', question: 'Reversal date when a document from a filed period is cancelled: cancel date or original date?', defaultAnswer: 'Cancel date + filed-period warning', when: 'Before go-live' },
  { id: 'ACC-10', group: 'accountant', question: "Classification of owner money (VERSION 2's ₱164,168; the Apps Script's hardcoded ₱500,000; each co-owner's injections): shares, deposit for subscription (FRB 6 conditions), or stockholder advances?", defaultAnswer: 'Advances from stockholders (2501) until classified', when: 'At cut-over' },
  { id: 'ACC-11', group: 'accountant', question: 'Does taking orders/payments online make Virtus an "e-commerce" taxpayer under RMC 98-2026 (e-invoicing by 31 Dec 2026)? Taxpayer class on BIR records (micro/small)? eFPS or eBIRForms?', defaultAnswer: 'Not e-commerce; small', when: 'Now (deadline 31 Dec 2026)' },
  { id: 'ACC-12', group: 'accountant', question: 'Numbering continuous (never reset yearly)?', defaultAnswer: 'Continuous', when: 'Before go-live' },
  { id: 'ACC-13', group: 'accountant', question: 'Inventory count frequency (monthly/yearly) and cost basis (latest cost/weighted average)?', defaultAnswer: 'Monthly count, latest purchase cost', when: 'Before first month-end' },
  { id: 'ACC-14', group: 'accountant', question: 'Refund of a deposit that had CWT: refund cash part and keep the credit, or refund gross?', defaultAnswer: 'Refund cash part; flag', when: 'Before go-live' },
  { id: 'ACC-15', group: 'accountant', question: 'Forfeited deposits: other income; VATable, needing an invoice?', defaultAnswer: 'Other income, not VATable, flagged', when: 'Before go-live', settingKey: 'col.forfeit_vatable' },
  { id: 'ACC-16', group: 'accountant', question: 'Depreciation policy per class (method, lives, residual); production equipment to cost of sales?', defaultAnswer: 'Straight-line; lives in E10; production → 5302', when: 'Before first month-end' },
  { id: 'ACC-17', group: 'accountant', question: 'Framework (PFRS for Small Entities?) and fiscal year', defaultAnswer: 'PFRS for SEs, calendar year', when: 'Before go-live' },
  { id: 'ACC-18', group: 'accountant', question: '13th month: accrue every run, or expense when paid?', defaultAnswer: 'Accrue every run', when: 'Before first payroll' },
  { id: 'ACC-19', group: 'accountant', question: 'Cost centres: production labor to cost of sales, office to admin?', defaultAnswer: 'Yes', when: 'Before first payroll' },
  { id: 'ACC-20', group: 'accountant', question: 'Payroll in two steps (run = accrual, release = payment)?', defaultAnswer: 'Two steps', when: 'Before first payroll' },
  { id: 'ACC-21', group: 'accountant', question: 'Statutory deductions: incremental month-to-date true-up each run; contribution month = period end?', defaultAnswer: 'Yes', when: 'Before first payroll' },
  { id: 'ACC-22', group: 'accountant', question: 'Corrections after a 2550Q/1601-EQ is filed: warning marker enough (no lock, per owner)?', defaultAnswer: 'Warning + "changes after filing" report', when: 'Before go-live' },
  { id: 'ACC-23', group: 'accountant', question: 'Post-dated checks: record when the check date arrives (memo list until then)?', defaultAnswer: 'Yes', when: 'Before go-live' },
  { id: 'ACC-24', group: 'accountant', question: 'Any government customers (5% VAT withholding)?', defaultAnswer: 'Supported; none assumed', when: 'Before go-live' },
  { id: 'ACC-25', group: 'accountant', question: 'SLSP submission format/threshold; SAWT preparation', defaultAnswer: 'Registers + CSV data', when: 'First quarter-end' },
  { id: 'OWN-01', group: 'owner', question: 'Remote access: NetBird free, Cloudflare Zero Trust free, or Tailscale Standard paid (remote users only)? Who needs remote access?', defaultAnswer: 'NetBird free', when: 'Before go-live' },
  { id: 'OWN-02', group: 'owner', question: 'Server PC, UPS, router, printers (see J5)', defaultAnswer: '—', when: 'Day 2' },
  { id: 'OWN-03', group: 'owner', question: 'Google account for off-site backups; who holds recovery keys A and B', defaultAnswer: 'Company Google account; owner + one co-owner', when: 'Day 2' },
  { id: 'OWN-04', group: 'owner', question: 'Payment terms list and Terms & Conditions text on quotations/JOs (old: mock-up approval, ±1.5 cm tolerance, 50% non-refundable downpayment, full payment before release, 7-day defect returns)', defaultAnswer: 'Keep the old four clauses', when: 'Day 3' },
  { id: 'OWN-05', group: 'owner', question: 'Piece-rate seed (49 rows): polo ₱60 or ₱70? NBA jersey ₱70 or ₱75? sublimated t-shirt ₱40 or ₱45? "Scrubsuit" = top only or top + pants? blouse ₱140?', defaultAnswer: 'Latest paid rate', when: 'Before first payroll' },
  { id: 'OWN-06', group: 'owner', question: "Each employee's daily rate vs the ₱550 Silang minimum; the monthly salary (₱15,000?)", defaultAnswer: 'Rates from payroll history, flagged', when: 'Before first payroll' },
  { id: 'OWN-07', group: 'owner', question: 'SSS/PhilHealth/Pag-IBIG/WTax ticked for everyone? Any legitimate exception? Government IDs', defaultAnswer: 'ON for all; untick needs a reason', when: 'Before first payroll' },
  { id: 'OWN-08', group: 'owner', question: 'Pay groups, periods and pay days (weekly piece Mon–Sat paid Saturday? semi-monthly 15th/30th?)', defaultAnswer: 'As F2', when: 'Before first payroll' },
  { id: 'OWN-09', group: 'owner', question: 'Cash advance policy: default instalment, minimum net pay, written authorization on file', defaultAnswer: 'Instalment typed per CA; minimum net ₱0 warning', when: 'Before first payroll' },
  { id: 'OWN-10', group: 'owner', question: 'Partial releases (some wearers first) allowed?', defaultAnswer: 'Yes', when: 'Day 3' },
  { id: 'OWN-11', group: 'owner', question: 'Customer emails (created, ready, claimed, statement): on or off? Sender address?', defaultAnswer: 'Off until configured', when: 'Later' },
  { id: 'OWN-12', group: 'owner', question: 'What encoders see: bank/GCash balances, payroll, sales totals', defaultAnswer: 'Cash on hand/petty cash only; no payroll; no sales totals', when: 'Day 1' },
  { id: 'OWN-13', group: 'owner', question: 'HTTPS via an app certificate installed once per device', defaultAnswer: 'Yes', when: 'Day 2' },
  { id: 'OWN-14', group: 'owner', question: 'Passwords: 15+ character passphrases, no forced expiry', defaultAnswer: 'Yes', when: 'Day 1' },
  { id: 'OWN-15', group: 'owner', question: 'Which customer/group do the 84 "MANUAL" measurement rows (5 batches) belong to?', defaultAnswer: 'Owner assigns on the import review screen', when: 'Before import' },
  { id: 'OWN-16', group: 'owner', question: 'Merge the 3 duplicate customer pairs? Which email is current for the pair with two?', defaultAnswer: 'Merge after review', when: 'Before import' },
  { id: 'OWN-17', group: 'owner', question: 'Status of the 52 old orders frozen at "Cutting" and the 5 released with a balance (₱306,890 open; are they collectible? invoiced?)', defaultAnswer: 'Owner/accountant tick per row in the opening checklist', when: 'Cut-over' },
  { id: 'OWN-18', group: 'owner', question: 'How to settle the old ₱3,900 cash-advance mismatch across 7 employees', defaultAnswer: 'Settle per employee before cut-over', when: 'Cut-over' },
  { id: 'OWN-19', group: 'owner', question: 'Keep the sizer tracker? Commissions paid to anyone? Collect birthdays for greetings?', defaultAnswer: 'Sizer later; no commissions; birthdays optional', when: 'Later' },
  { id: 'OWN-20', group: 'owner', question: 'University (15 department records) and hospital (2): one customer with departments as groups, or separate customers linked to a parent?', defaultAnswer: 'Parent + child customers (departments pay separately), groups inside', when: 'Before import' },
  { id: 'OWN-21', group: 'owner', question: 'JO fields editable without reissue (due date, priority, notes, route, attachments, roster corrections keeping quantities)', defaultAnswer: 'As listed', when: 'Day 2' },
  { id: 'OWN-22', group: 'owner', question: 'Who may release goods with an unpaid balance?', defaultAnswer: 'Owner and accountant', when: 'Day 3' },
  { id: 'OWN-23', group: 'owner', question: 'Purchase orders editable until first receiving', defaultAnswer: 'Yes', when: 'Day 3' },
  { id: 'OWN-24', group: 'owner', question: 'Add a Quality Check step?', defaultAnswer: 'No (off)', when: 'Day 3' },
  { id: 'OWN-25', group: 'owner', question: 'Rework ("pasubra"): paid? at what rate?', defaultAnswer: 'Paid at a rework rate typed per entry', when: 'Before first payroll' },
  { id: 'OWN-26', group: 'owner', question: 'Who may override a piece rate?', defaultAnswer: 'Encoders (logged with reason)', when: 'Day 3' },
  { id: 'OWN-27', group: 'owner', question: 'Cash balances visible to encoders', defaultAnswer: 'See OWN-12', when: 'Day 2' },
  { id: 'OWN-28', group: 'owner', question: 'Are any of the 4–5 "Board Member" records on payroll (salary) or paid directors\' fees?', defaultAnswer: 'Not on payroll', when: 'Before first payroll' },
  { id: 'OWN-29', group: 'owner', question: 'Local Cavite/Silang special days to add to the holiday calendar', defaultAnswer: 'National list only', when: 'Before first payroll' },
  { id: 'OWN-30', group: 'owner', question: 'Which bank accounts print on quotations/statements (company accounts only)?', defaultAnswer: 'Company BDO/China Bank/GCash only', when: 'Day 2' },
  { id: 'OWN-31', group: 'owner', question: 'Import VERSION 2 transaction history?', defaultAnswer: 'No: master data from the Apps Script sheet only; VERSION 2 archived read-only', when: 'Now' },
  { id: 'CO-01', group: 'co-owners', question: 'One switch-over date agreed by all three owners; old apps read-only after it', defaultAnswer: 'Proposed: the Sunday after the second test day, then side-by-side 1–2 weeks', when: 'Before test days' },
  { id: 'CO-02', group: 'co-owners', question: 'Who gets the Owner role (all three owners; nobody else)', defaultAnswer: 'The three owners', when: 'Day 1' },
  { id: 'CO-03', group: 'co-owners', question: "How each owner's past money into the company was made (for ACC-10)", defaultAnswer: '—', when: 'Cut-over' },
];

/** The six separate go-live requirements in PLAN B4. */
export const GO_LIVE_REQUIREMENTS: DecisionDefinition[] = [
  { id: 'LIVE-01', group: 'owner', question: 'All Must-tier items are done.', defaultAnswer: 'Done', when: 'Before go-live' },
  { id: 'LIVE-02', group: 'accountant', question: 'The month-in-the-life golden scenario and blind recompute by both reviewers agree to the centavo.', defaultAnswer: 'Done', when: 'Before go-live' },
  { id: 'LIVE-03', group: 'owner', question: 'The import rehearsal passed its count and checksum gates.', defaultAnswer: 'Done', when: 'Before go-live' },
  { id: 'LIVE-04', group: 'owner', question: 'A restore drill succeeded on the shop PC.', defaultAnswer: 'Done', when: 'Before go-live' },
  { id: 'LIVE-05', group: 'owner', question: 'Every print was test-printed on the shop printers.', defaultAnswer: 'Done', when: 'Before go-live' },
  { id: 'LIVE-06', group: 'accountant', question: 'The accountant signed off the opening trial balance and every Part K decision marked “Before go-live”.', defaultAnswer: 'Done', when: 'Before go-live' },
];

export const GO_LIVE_DECISIONS = [...PART_K_DECISIONS, ...GO_LIVE_REQUIREMENTS];
