import { beforeEach,describe,expect,it } from 'vitest';
import { createTestEnv,idem,type Client,type TestEnv } from '../../../../test/helpers.ts';
let env:TestEnv,accountant:Client,encoder:Client,owner:Client;
beforeEach(async()=>{env=await createTestEnv();accountant=await env.as('accountant');encoder=await env.as('encoder');owner=await env.as('owner')});
describe('RPT supplier, cash, asset and control reports',()=>{
 it('takes cash position from the same ledger as the trial balance',async()=>{const id=env.db.prepare("SELECT id FROM accounts WHERE code='1101'").pluck().get() as number;const income=env.db.prepare("SELECT id FROM accounts WHERE code='7103'").pluck().get() as number;await accountant.post('/api/docs/acc.jv/post',{input:{memo:'Made-up shop cash receipt',lines:[{accountId:id,debitCents:12345},{accountId:income,creditCents:12345}]},expectedTotalCents:12345},idem());const cash=await accountant.get('/api/rpt/cash-position?asOf=2026-09-29');expect(cash.statusCode,cash.body).toBe(200);expect(cash.json().rows.find((r:{id:number})=>r.id===id).balanceCents).toBe(12345);const tb=await accountant.get('/api/rpt/trial-balance?asOf=2026-09-29');expect(tb.json().rows.find((r:{code:string})=>r.code==='1101').debitCents).toBe(12345);});
 it('exports CSV and denies a role without report permission on every report',async()=>{const routes=['ap-aging?asOf=2026-09-29','purchases?from=2026-09-01&to=2026-09-29','purchase-orders','received-not-billed','cash-position?asOf=2026-09-29','transfers?from=2026-09-01&to=2026-09-29','cash-counts?from=2026-09-01&to=2026-09-29','assets?asOf=2026-09-29','late-entries','cancellations','exceptions?asOf=2026-09-29'];for(const route of routes){expect((await encoder.get(`/api/rpt/${route}`)).statusCode,route).toBe(403);const csv=await accountant.get(`/api/rpt/${route}${route.includes('?')?'&':'?'}format=csv`);expect(csv.statusCode,csv.body).toBe(200);expect(csv.headers['content-type']).toContain('text/csv');}});
 it('reserves sign-in history for owners',async()=>{const route='/api/rpt/sign-ins?from=2026-09-01&to=2026-09-29';expect((await accountant.get(route)).statusCode).toBe(403);expect((await encoder.get(route)).statusCode).toBe(403);const csv=await owner.get(`${route}&format=csv`);expect(csv.statusCode,csv.body).toBe(200);expect(csv.headers['content-type']).toContain('text/csv');});
});
